### ISSUE TITLE
support es6/imports

### ISSUE THREAD

**Issue by joeyfigaro** [abou7mied/detect-circular-deps#1]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/0m2W272r2C2A3h1b1A2w/Image%202018-09-13%20at%201.10.08%20PM.png?X-CloudApp-Visitor-Id=1332463&v=8b70da19)

**Comment by abou7mied** [comment]
Hi @joeyfigaro, thanks for reporting.

Actually this tool is designed to work in Node.js environment, es6/imports isn't supported yet in nodeJS (except running node with [--experimental-modules](https://nodejs.org/api/esm.html)) .

You can use a transpiler such as **babel** to convert es6 to es5 and run the tool on the results.

The second option that there is a lib called **babel-register** which can convert es6 to es5 at runtime but I don't know if it will work as excepted or not, so I'm going to give it a try this night and update the tool if it worked properly.

**Comment by abou7mied** [comment]
Hi @joeyfigaro I have released a new update to [support es6 imports](https://github.com/abou7mied/detect-circular-deps#support-es6-importexport). Please feel free to test it out and let me know if the issue wasn't fixed
